### ISSUE TITLE
Ability to filter containers on selectors

### ISSUE THREAD

**Issue by eligne-pro** [logzio/docker-collector-logs#13]
Filtering pods through their name is a bit limitative in Kubernetes cluster where pods are organized in namespaces and labels.
Is there a way to use a kubernetes selector?

**Comment by idohalevi** [comment]
@eligne-pro I think [this](https://github.com/logzio/logzio-k8s) repo is more suitable for your needs. In that project, you can change the configuration to filter the pods. Another option is to use Logz.io [drop filters](https://docs.logz.io/user-guide/accounts/drop-filters/) feature

**Comment by LeandroFranciscato** [comment]
Hi, about that: 
How would I use the `matchContainerName` to filter my container name?
I've tried a bunch of filters (regex or not) and when I do that it doesn't send any logs anymore.

Posting part of the yml:

```yml
...
spec:
  containers:
  - name: docker-collector-logs
    image: logzio/docker-collector-logs
    env:
      - name: LOGZIO_TOKEN
        value: token
      - name: LOGZIO_URL
        value: url
      - name: matchContainerName
        value: 1p-agent
    volumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
  - name: 1p-agent
    image: image/mine
    imagePullPolicy: Always
    env:
      - name: VAR1
        value: 1
      - name: VAR2
        value: 2
    resources:
...
```
