### ISSUE TITLE
docker-compose example

### ISSUE THREAD

**Issue by PabloCastellano** [logzio/docker-collector-logs#55]
Hello, I have added the following piece of code to my docker-compose file:

```
  logz:
    image: logzio/docker-collector-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
      LOGZIO_TOKEN: "xxxx"
```

However only the logs from the docker-collector-logs container are sent. Could you provide a working example?
